export const userTypes={
    USER_STATE_CHANGE:  "USER_STATE_CHANGE",
   SIGN_IN_SUCCESS:  "SIGN_IN_SUCCESS",
   SIGN_UP_SUCCESS:  "SIGN_UP_SUCCESS",
   SIGN_UP_ERROR:  " SIGN_UP_ERROR",
   RESET_PASSWORD_SUCCESS:  "RESET_PASSWORD_SUCCESS",
   RESET_PASSWORD_ERROR:"   RESET_PASSWORD_ERROR",
   RESET_AUTH_FORMS:" RESET_AUTH_FORMS"

    }