
 const productsTypes ={
      ADD_NEW_PRODUCTS_START:" ADD_NEW_PRODUCTS_START",
      FETCH_PRODUCTS_START:"FETCH_PRODUCTS_START",
     SET_PRODUCTS_START:" SET_PRODUCTS_START",
     DELETE_PRODUCTS_START:"DELETE_PRODUCTS_START"
    
    
}
export default productsTypes
