
 const productsTypes ={
     ADD_NEW_PRODUCTS_START:" ADD_NEW_PRODUCTS_START",
     FETCH_PRODUCTS_START:"FETCH_PRODUCTS_START",
     SET_PRODUCTS_START:" SET_PRODUCTS_START",
     DELETE_PRODUCT_START:"DELETE_PRODUCT_START",
     FETCH_PRODUCT_START:"  FETCH_PRODUCT_START",
     SET_PRODUCT:"SET_PRODUCT"
    
    
}
export default productsTypes
